version: '3.4'

services:
  mongodb:
    container_name: mongodb
    image: mongo:5.0.2-focal
    volumes:
      - mongodb-vol:/data/db:cached
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: mongodb
volumes:
  mongodb-vol:
    name: mongodb-vol
